### PR TITLE
Update php.ts

### PR DESCRIPTION
**Pull request by WinterSilence**
Add [magic constants](https://www.php.net/manual/en/language.constants.magic.php)
Add `self` keywords
Extend [list of keywords](https://www.php.net/manual/en/reserved.keywords.php)
Group variable types

### CODE REVIEW

**Comment by WinterSilence** [comment]
Also need help with adding class constants

**Comment by marijnh** [comment]
Many of these don't seem to actually be emitted by the parser. Defining a highlighting tag for a name that won't appear in the parse tree doesn't actually work.

**Comment by WinterSilence** [comment]
@marijnh you mean many in this PR or at all?

**Comment by marijnh** [comment]
In this PR.

**Comment by WinterSilence** [comment]
@marijnh 

> Defining a highlighting tag for a name

I'm add only `self` keywords and magic constants, in other cases I'm only append missed keywords. please, specify exactly what's wrong?

**Comment by marijnh** [comment]
These changes don't work, for things like `__CLASS__`, as I'm sure you can confirm. The names in this context refer to syntax tree node names, so you can't just define new constants here.

**Comment by WinterSilence** [comment]
@marijnh ok, constants are removed. anything else?

**Comment by marijnh** [comment]
Attached patch adds the ones that were missed. The others don't exist in the parser output.

**Comment by WinterSilence** [comment]
@marijnh why `declare enddeclare` not in control keywords? why `eval isset empty die exit __halt_compiler` don't exist in the parser output?

**Comment by marijnh** [comment]
> @marijnh why declare enddeclare not in control keywords?

Oh, I see, they were already there in definition keywords, which seems a reasonable place for them as well. My patch actually adds them to control keywords.

> why eval isset empty die exit __halt_compiler don't exist in the parser output?

Mostly because they didn't appear in the tree-sitter grammar our grammar is based on, which I guess is because you still get a reasonable parse even if you don't handle these specially.

**Pull request closed without merging**
